BP/bigsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from user.views import activate_account
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index, name='main'),
    path('about/',views.about, name='about'),
    path("board/", include('board.urls', namespace = 'board')),
    path("user/", include('user.urls', namespace = 'user')),
    path("book/", include('book.urls', namespace = 'book')),
    path("quiz/", include('quiz.urls', namespace = 'quiz')),
    path("personal/", include('personal.urls', namespace = 'personal')),
    path("recommend/", include('recommend.urls', namespace = 'recommend')),
    path('activate/<str:uidb64>/<str:token>/', activate_account, name='activate_account'),
    path('accounts/', include('allauth.urls')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/book/urls.py
# book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.list, name='list'),
    path('detail', views.detail, name='detail'),
    path('detail/<isbn>', views.detail, name='detail'),
    path('child', views.list_child, name='list_child'),
]

BP/user/urls.py
# user_app/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('register/', views.user_form_view, name='register'),
    path('register/check-username/', views.check_username, name='check_username'),
    path('select/', views.select, name='select'),
    path('login/', views.login_view, name='login'),
    path('forgot_id/', views.forgot_id, name='forgot_id'),
    path('forgot_pw/', views.forgot_pw, name='forgot_pw'),
    path('forgot_pw/<str:uid>/<str:token>/', views.forgot_pw, name='forgot_pw'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('mypage/', views.mypage, name='mypage'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete_check, name='delete_check'),
    path('delete_/', views.delete_real, name='delete_real'),
]

BP/user/forms.py
from django import forms
from user.models import User, user_favor
import hashlib
from django.contrib.auth.forms import UserChangeForm
import re

class UserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    email_front = forms.CharField(label='이메일')
    domain_choice = forms.ChoiceField(
        label='도메인 선택',
        choices=[('custom', '직접입력'), ('naver.com', 'naver.com'), ('gmail.com', 'gmail.com')],
        initial='직접입력'
    )
    custom_domain = forms.CharField(label='직접입력', required=False)

    class Meta:
        model = User
        fields = ['username', 'phone', 'email_front', 'custom_domain', 'name', 'nickname', 'birth', 'gender']
        
    def clean_password(self):
        password1 = self.cleaned_data.get('password1')
        if password1 is None:
            True #already print error
        else:
            if len(password1) < 8:
                self.add_error("password1", "비밀번호는 8글자 이상이어야 합니다.")
            if not re.search(r'\d', password1) or not re.search(r'[a-zA-Z]', password1) or not re.search(r'[^a-zA-Z0-9]', password1):
                self.add_error("password1", "숫자, 문자, 특수문자를 각각 하나 이상 포함해야 합니다.")
        return password1

    def clean(self):
        cleaned_data = super().clean()
        #비밀번호 예외처리
        password1 = self.clean_password()
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            self.add_error('password2', "비밀번호 확인이 일치하지 않습니다.")
        #이메일 예외처리
        email_front = self.cleaned_data.get('email_front')
        domain_choice = self.cleaned_data.get('domain_choice')
        custom_domain = self.cleaned_data.get('custom_domain')
            
        if domain_choice != 'custom':
            custom_domain = domain_choice
        cleaned_data['email'] = str(email_front) + '@' + str(custom_domain)
        email = self.cleaned_data.get('email')
        
        if email_front is None:
            True #already print error
        elif custom_domain == "":
            self.add_error('email_front', '도메인을 입력해주세요.')
        elif '.' not in custom_domain or custom_domain.split('.')[1] == '':
            self.add_error('email_front', '잘못된 도메인 형식입니다.')
        return cleaned_data
  
    def save(self, commit=True):
        user = super().save(commit=False)
        user.password = hashlib.sha256(self.cleaned_data.get('password1').encode()).hexdigest()
        user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        
        return user

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['phone', 'nickname', 'name']
    
    
class UserFavorForm(forms.ModelForm):
    class Meta:
        model = user_favor
        fields = ['username', 'favor1', 'favor2', 'favor3', 'favor4']

BP/user/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.shortcuts import redirect
from django.core.mail import EmailMessage
from user.forms import UserForm
from user.models import user_favor
from static.python.render_support import *
from .forms import EditProfileForm, UserFavorForm
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from django.http import JsonResponse
import re, hashlib

User = get_user_model()

def user_form_view(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active=False            
            user.save()
            # 이메일 인증 URL 생성
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)
            activation_url = request.build_absolute_uri(f'/activate/{uid}/{token}/')

            # 인증 이메일 전송
            email_subject = '책크미 계정을 인증해주세요'
            email_body = f'다음 링크를 클릭해 책크미 계정을 인증해주세요: {activation_url}'
            from_email = 'noreply@chaekme.com'
            email = EmailMessage(email_subject, email_body, from_email=from_email, to=[form.cleaned_data['email']])
            email.send()

                
            return n_render(request, 'user/active_required.html', {'email':user.email})# 회원가입 성공
    else:
        form = UserForm()
        
    
        
    data = {
        "form" : form,
    }
        
    return n_render(request, 'user/register.html', {"form": form})      # 회원가입 실패

def check_username(request): #아이디 중복 확인
    errorname = "couldn't get"
    try:
        username = request.GET['username']
        errorname = "couldn't sql"
        if username:
            exists = User.objects.filter(username=username).exists()
            errorname = "couldn't return"
            return JsonResponse({'exists': exists})
    except:
        return JsonResponse({'error': errorname})

#이메일 인증 URL 접근 > is_active 활성화 뷰
def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return n_render(request, 'user/active_response.html', {'username':user.username})  # 계정 활성화 성공
    else:
        return redirect('user:login')  # 계정 활성화 실패

#로그인 처리 뷰
def login_view(request):
    #로그인 폼 제출 시
    if request.method == 'POST':
        username = request.POST['username']
        password = hashlib.sha256(request.POST['password'].encode()).hexdigest()
        # 사용자 인증
        user = authenticate(request, username=username, password=password)
        if user is not None:  #로그인 성공
            login(request, user=user)
            request.session['id'] = str(user)
            return redirect('main')
        else: #로그인 실패
            return n_render(request, 'user/login.html', {'error': '아이디 혹은 비밀번호 오류입니다.'})
    #초기 페이지
    else:
        return n_render(request, 'user/login.html')

def select(request):
    #선호 장르 4개 선택지 제출할 경우
    if request.method == "POST":
        username = str(request.user)
        genres = request.POST['summary'].split('|||')
        try:
            form = user_favor.objects.get(username=username)
        except user_favor.DoesNotExist:
            form = None
        
        form_data = {
            'username': username,
            'favor1': genres[0],
            'favor2': genres[1],
            'favor3': genres[2],
            'favor4': genres[3]
        }
        if form:
            form = UserFavorForm(data=form_data, instance=form)
        else:
            form = UserFavorForm(data=form_data)
        if form.is_valid():
            form.save()
            return redirect('main')
    #초기 페이지
    novel = []
    novel.append(["한국", "50917"])
    novel.append(["일본", "50918"])
    novel.append(["영미", "50919"])
    novel.append(["스페인/중남미", "50920"])
    novel.append(["프랑스", "50921"])
    novel.append(["독일", "50922"])
    novel.append(["중국", "50923"])
    novel.append(["러시아", "52650"])
    novel.append(["세계", "50925"])
    novel.append(["추리/미스터리", "50926"])
    novel.append(["판타지/환상문학", "50928"])
    novel.append(["역사", "50929"])
    novel.append(["과학(SF)", "50930"])
    novel.append(["호러/공포", "50931"])
    novel.append(["무협", "50932"])
    novel.append(["액션/스릴러", "50933"])
    novel.append(["로맨스", "50935"])
    
    essay = []
    essay.append(["한국", "51371"])
    essay.append(["외국", "51373"])
    essay.append(["동물", "174700"])
    essay.append(["명상", "51374"])
    essay.append(["심리치유", "51375"])
    essay.append(["사진/그림", "51376"])
    essay.append(["음식", "180236"])
    essay.append(["여행", "51377"])
    essay.append(["독서", "51380"])
    essay.append(["예술", "51842"])
    essay.append(["종교", "51389"])
    essay.append(["사랑/연애", "51391"])
    essay.append(["노년", "51392"])
    essay.append(["자연", "51394"])
    essay.append(["명언/잠언록", "51398"])
    essay.append(["일기/편지", "51402"])
    essay.append(["유머/풍자/우화", "51404"])
    essay.append(["포켓", "51408"])
    essay.append(["작은 이야기 모음", "51413"])
    essay.append(["명사", "51416"])
    
    self = []
    self.append(["성공", "70214"])
    self.append(["리더십", "70212"])
    self.append(["행복론", "70211"])
    self.append(["인간관계", "2951"])
    self.append(["힐링", "70236"])
    self.append(["심플라이프", "107822"])
    self.append(["협상/설득/화술", "70224"])
    self.append(["프레젠테이션", "70233"])
    self.append(["기획/보고", "70228"])
    self.append(["시간/정보관리", "70220"])
    self.append(["두뇌계발", "70223"])
    self.append(["취업/진로", "2943"])
    self.append(["20대의 자기계발", "70241"])
    self.append(["여성의 자기계발", "70218"])
    self.append(["중년의 자기계발", "70219"])
    
    data = {
        "novels":novel,
        "essays":essay,
        "selfs":self,
    }
    return n_render(request, 'user/select.html', data)

def edit(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('user:mypage')
    else:
        form = EditProfileForm(instance=request.user)
    
    return n_render(request, 'user/edit.html', {'form': form})

def change_password(request):  
    if request.user.is_anonymous:
        redirect('main')
    username = request.user.username
    if request.method == 'POST' and request.POST.get('password1') is not None:
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 != password2:
            return n_render(request, 'user/change_password.html', {'error': '패스워드 확인이 일치하지 않습니다.'})
        elif len(password1) < 8:
            return n_render(request, 'user/change_password.html', {'error': '비밀번호는 숫자, 문자, 특수문자를 포함해 8자리 이상이어야 합니다.'})
        elif not re.search(r'\d', password1) or not re.search(r'[a-zA-Z]', password1) or not re.search(r'[^a-zA-Z0-9]', password1):
            return n_render(request, 'user/change_password.html', {'error': '비밀번호는 숫자, 문자, 특수문자를 포함해 8자리 이상이어야 합니다.'})
        hashed_password = hashlib.sha256(password1.encode()).hexdigest()
        user = User.objects.get(username=request.user.username)
        user.password = hashed_password
        user.save()
        if user is not None:
            user = authenticate(request, username=username, password=hashed_password)
            login(request, user=user)
        return redirect('user:mypage')
    else:
        return n_render(request, 'user/change_password.html')

def delete_check(request):
    return n_render(request, 'user/delete_check.html', login_essential=1)

def delete_real(request):
    if request.method == 'POST':
        user = request.user
        if user:
            user.delete()
            return redirect('user:logout')
    return redirect('user:delete_real')

def mypage(request):
    return n_render(request,'user/mypage.html', login_essential=1)

class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def pre_social_login(self, request, sociallogin):
        if sociallogin.is_existing:
            pass
        else:        
            if sociallogin.account.provider=='kakao':
                email = sociallogin.account.extra_data['kakao_account']['email']
            elif sociallogin.account.provider=='google':
                email = sociallogin.account.extra_data['email']
            else:
                email = None
            if email:
                existing_user = User.objects.filter(email=email).first()
                if existing_user:
                    if not existing_user.is_active:
                        existing_user.is_active = 1
                        existing_user.save()
                    sociallogin.connect(request, existing_user)
    def populate_user(self, request, sociallogin, data):
        user = super().populate_user(request, sociallogin, data)
        # 사용자 정보 처리 및 User 모델에 저장 로직 추가
        user.is_active=1
        if sociallogin.account.provider == 'google':
            # 구글 로그인인 경우
            user.name = sociallogin.account.extra_data['name']
            user.nickname = sociallogin.account.extra_data['name']
            user.email = sociallogin.account.extra_data['email']
        elif sociallogin.account.provider == 'kakao':
            # 카카오 로그인인 경우
            if 'username' in data:
                if data['username']:
                    user.name = data['username']
            if 'profile_image' in data:
                if data['profile_image']:
                    user.img_src = data['profile_image']
            if 'email' in data:
                if data['email']:

BP/templates/user/active_required.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
<script type="text/javascript" src="{% static 'js/user.js' %}"></script>
{% endblock %}

{% block content %}
<div class="email-img">
    <img class='img' src="/static/images/email_img.png">
</div>
<div class="email-content">
    <h2>
        {{email}}<br>
        인증 메일이 발송되었습니다.
        <br>
        인증을 완료해주세요.
    </h2>
    <h3>
        <br>
        인증 전까지 계정은 비활성화 됩니다.
    </h3>
</div>
{% endblock %}

BP/templates/user/active_response.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
<script type="text/javascript" src="{% static 'js/user.js' %}"></script>
{% endblock %}

{% block content %}
<div class="email-img">
    <img class='img' src="/static/images/email_img.png">
</div>
<div class="email-content">
    <h2>
        {{email}}<br>
        이메일 인증이 완료되었습니다.
        <br>
    </h2>
    <h3>
        <br>
        즐거운 책크미 되세요!
    </h3>
</div>
{% endblock %}

BP/templates/user/change_password.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block content %}
<h1 style='margin:50px;'>비밀번호 변경</h1>
<form method="post" action="{% url 'user:change_password' %}">
    {% csrf_token %}
    <div class='userbox2'>
        <div class = 'input_divs'>
            <label style='width: 190px;'>Password</label>&emsp;<input type = "password" placeholder="Password" class = "input_1" name = "password1" value = "{{ form.password1.value|default_if_none:'' }}">
        </div>
    </div>
    
    <div class='userbox2'>
        <div class = 'input_divs'>
            <label style='width:190px;'>PW confirm</label>&emsp;<input type = "password" placeholder="PW confirm" class = "input_1" name = "password2" value = "{{ form.password2.value|default_if_none:''}}">
        </div>
    </div>            
    {% if error %}
    <div class="error_message">{{ error }}</div>
    {% endif %}
    <div class='edit_btn'>
        <button style='width:100px;margin-top:50px;' type="submit" class = "button_1 yn_btn">변경</button>
        <button style='width:100px;margin-top:50px;' class = "button_1 yn_btn" type="button" onclick = "window.location='{% url 'user:mypage' %}';">취소</button>
    </div>
</form>


{% endblock %}

BP/templates/user/edit.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}


{% block content %}
  <h1>회원 정보 수정</h1>
  <form method="post" action="{% url 'user:edit' %}">
    {% csrf_token %}
    <div class='userbox2'>
        <div class = 'input_divs'>
            <div class='first'><label>Name</label></div>&emsp;<input type = "text" class = "input_1" name = "name" placeholder= {{user.name}} value = "{{ form.name.value|default_if_none:user.name}}">
        </div>
    </div>

    <div class='userbox2'>
        <div class = 'input_divs'>
            <div class='first'><label>Nickname</label></div> &emsp;<input type = "text" class = "input_1" name = "nickname" placeholder= {{user.nickname}} value = "{{ form.nickname.value|default_if_none:user.nickname}}">
        </div>
    </div>

    <div class='userbox2'>
        <div class = 'input_divs'>
            <div class='first'><label>Phone</label></div>&emsp;<input type = "text" class = "input_1" name = "phone" placeholder = {{user.phone}} value = "{{ form.phone.value|default_if_none:user.phone}}">
        </div>
    </div>

    <div class='edit_btn'>
        <button type="submit" class = "yn_btn">수정</button>
        <button class = "yn_btn" type="button" onclick = "window.location='{% url 'user:mypage' %}';">취소</button>
    </div>
    </form>


{% endblock %}

BP/templates/user/forgot_id.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block content %}
<h1>아이디 찾기</h1>

<form method="post" action="{% url 'user:forgot_id' %}" entype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="input_divs">
        <input type="text" class="input_1" 
            name="email" id="email" placeholder= "email" value="{{ form.email.value|default_if_none:""}}">
    </div>
    {% if error %}
    <div class="error_message">{{ error }}</div>
    {% endif %}
<br>
가입 시 작성하신 이메일 주소로 본인 아이디가 전송됩니다.
<br>

    <div class='innerdiv' id='weight3'>
        <button style='width:100px;margin-top:50px;' class = "button_1" type="submit" >확인</button>
    </div>
    <button style='width:100px;margin-top:50px;' class="button_1" type="button" onclick="window.location='{% url 'user:login' %}';">취소</button>
</form>



{% endblock %}

BP/templates/user/forgot_pw.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block content %}
<h1>비밀번호 변경</h1>

<form method="post" action="{% url 'user:forgot_pw' %}" entype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="input_divs">
        <input type="text" class="input_1" 
            name="username" id="username" placeholder= "ID" value="{{ form.username.value|default_if_none:""}}">
    </div>
    {% if error %}
    <div class="error_message">{{ error }}</div>
    {% endif %}
    <div class='innerdiv' id='weight3'>
        <button style='width:100px;margin-top:50px;' class="button_1" type="submit">확인</button>
    </div>
    <button style='width:100px;margin-top:50px;' class="button_1" type="button" onclick="window.location='{% url 'user:login' %}';">취소</button>
</form>

{% comment %} <small>발급받은 아이디를 공백 없이 정확하게 입력해주세요.</small> {% endcomment %}

{% comment %} <div class="input_divs">
    <div class="innerdiv" id="weight5">
        <input type="text" class="input_1" placeholder= "email" name="email_front">
    </div>
    <div class="innerdiv" id="weight1">
        @
    </div>
    <div class="field-wrapper">
        {{ form.custom_domain }} {{ form.domain_choice }}
    </div>
</div>

{% if form.errors.email %}
<div class="error_message">{{ form.errors.email }}</div>
{% endif %}

<script>
    // 도메인 선택 시 custom_domain 필드 업데이트
    document.getElementById("id_domain_choice").addEventListener("change", function() {
        var domainChoice = this.value;
        if (domainChoice === "custom") {
            document.getElementById("id_custom_domain").disabled = false;
            document.getElementById("id_custom_domain").value = "";
        } else {
            document.getElementById("id_custom_domain").disabled = true;
            document.getElementById("id_custom_domain").value = domainChoice;
        }
    });
</script> {% endcomment %}

<br>
가입 시 작성하신 이메일 주소로 해당 아이디의 비밀번호 변경 링크가 전송됩니다.
<br>




{% endblock %}

BP/templates/user/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block content %}
<div class="login-wrapper">
    <div class="login-content">
        <h2 class="login-title">LogIn</h2>
        <form class="login-form validated-form" id="login-form" name="login-form" method="post" action="{% url 'user:login' %}" novalidate="novalidate" entype="application/x-www-form-urlencoded">
            {% csrf_token %}
            <div class="login-input-wrapper">
                <input class="login-email" id="email" name="username" type="text" placeholder="ID" name="username" id="username" value="{{ form.username.value|default_if_none:""}}">
            </div>
            <div class="login-input-wrapper">
                <input class="login-password" type="password" placeholder="Password" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
            </div>
            {% if error %}
            <div class="error_message">{{ error }}</div>
            {% endif %}
            <button style='width:340px;margin-top:13px;' class="btn-login">LogIn</button>
            <div class='service-btn'>
                <a class="login-link" href="{% url 'user:register' %}">Register</a>
                <a>&nbsp;|&nbsp;</a>
                <a class="login-link" href="{% url 'user:forgot_id' %}">Forgot ID?</a>
                <a>&nbsp;|&nbsp;</a>
                <a class="login-link" href="{% url 'user:forgot_pw' %}">Forgot password?</a>
            </div>

            </form>
            <hr>
    </div>
</div>
<div class="social">
    {% load socialaccount %} 
    <div class='btn-google'>
        <a href="{% provider_login_url 'google' %}" target="_blank">
            <img src="{% static 'images/google_icon.PNG' %}" alt="위의 이미지를 누르면 연결됩니다." class='icon_img'>
            <h4 style='margin-right:12px;'>Login with Google</h4>
        <a>
        
    </div>
    <div class='btn-kakao'>
        <a href="{% provider_login_url 'kakao' %}" target="_blank">
            <img src="{% static 'images/kakao_icon.PNG' %}" alt="위의 이미지를 누르면 연결됩니다." class='icon_img'>
            <h4 style='margin-right:20px;'>Login with Kakao</h4>
        <a>
    </div>
</div>
{% endblock %}

BP/templates/user/mypage.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}
{% block content %}
<h1>회원 정보</h1>
<div class='userbox'>
<div class = 'first'><label>Name</label></div><div>{{user.name}}</div>
</div>
<div class='userbox'>
    <div class = 'first'><label>Nickname</label></div><div>{{user.nickname}}</div>
</div>
<div class='userbox'>
    <div class = 'first'><label>ID</label></div><div>{{user.username}}</div>
</div>
<div class='userbox'>
    <div class = 'first'><label>Email</label></div><div>{{user.email}}</div>
</div>
<div class='userbox'>
    <div class = 'first'><label>Phone</label></div><div>{{user.phone}}</div>
</div>

    {% if user.is_authenticated %}
    <div class = 'submit' style='margin-left:40px;margin-top:40px;'>
        <form action="{% url 'user:edit' %}" method="POST">
            {% csrf_token %}
            <button class = "button_1" type="submit">정보수정</button>
        </form> 
        <form action="{% url 'user:change_password' %}" method="POST">
            {% csrf_token %}
            <button class = "button_1" type="submit" >PW수정</button>
        </form> 
        <form action="{% url 'user:select' %}" method="GET">
            {% csrf_token %}
            <button class = "button_1" type="submit" >장르변경</button>
        </form>

        <form action="{% url 'user:delete_check' %}" method="POST">
            {% csrf_token %}
            <button class = "button_1" type="submit" >회원탈퇴</button>
        </form>

        
    </div>
    {% endif %}
</div>
{% endblock %}