BP/bigsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from user.views import activate_account
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index, name='main'),
    path('about/',views.about, name='about'),
    path("board/", include('board.urls', namespace = 'board')),
    path("user/", include('user.urls', namespace = 'user')),
    path("book/", include('book.urls', namespace = 'book')),
    path("quiz/", include('quiz.urls', namespace = 'quiz')),
    path("personal/", include('personal.urls', namespace = 'personal')),
    path("recommend/", include('recommend.urls', namespace = 'recommend')),
    path('activate/<str:uidb64>/<str:token>/', activate_account, name='activate_account'),
    path('accounts/', include('allauth.urls')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/book/urls.py
# book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.list, name='list'),
    path('detail', views.detail, name='detail'),
    path('detail/<isbn>', views.detail, name='detail'),
    path('child', views.list_child, name='list_child'),
]

BP/recommend/urls.py
# quiz/urls.py
from django.urls import path
from . import views

app_name = 'recommend'
urlpatterns = [
    path('', views.index, name='index'),
    path('loading/', views.loading, name='loading'),
    path('prog', views.prog, name='prog'),
    path('end', views.end, name='end'),
]

BP/recommend/models.py
from django.db import models

# Create your models here.

class Genre(models.Model) :
    title = models.TextField()
    isbn13 = models.TextField()
    categories = models.TextField(null=True)
    cover = models.TextField()
    def __str__(self):
        return self.name

BP/recommend/views.py
import sys
import random

# setting path
sys.path.append('../static')

from static.python.render_support import *
from static.python.book_recommend import *
from .models import Genre

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:login') + "?alert=로그인 이후에 이용하실 수 있습니다.")
    return n_render(request,'recommend/index.html')


def prog(request): # 52 genre 
    genres = ['한국소설','일본소설','영미소설','스페인/중남미소설',
'프랑스소설','독일소설','중국소설','러시아소설','세계의 소설',
'추리/미스터리소설','판타지/환상문학','역사소설','과학소설(SF)',
'호러.공포소설','무협소설','액션/스릴러소설','로맨스소설','한국에세이',
'외국에세이','동물에세이','명상에세이','심리치유 에세이','사진/그림 에세이',
'음식에세이','여행에세이','독서에세이','예술에세이','종교에세이',
'사랑/연애 에세이','노년을 위한 에세이','자연에세이','명언/잠언록',
'일기/편지','유머/풍자/우화','포켓에세이','작은 이야기 모음',
'명사에세이','성공','리더십','행복론','인간관계','힐링',
'정리/심플라이프','협상/설득/화술','프레젠테이션/회의','기획/보고',
'시간관리/정보관리','창의적사고/두뇌계발','취업/진로/유망직업',
'20대의 자기계발','여성의 자기계발','중년의 자기계발']
    book_selection = {}
    gen = []
    all_books = Genre.objects.all()
    available_books = list(all_books)

    for genre in genres:
        # 해당 장르를 포함하는 책들을 가져옴
        books_in_genre = all_books.filter(categories__icontains=genre)
        
        if books_in_genre.exists():
  
            # 사용 가능한 책들 중에서 임의의 책 선택
            selected_book = random.choice(books_in_genre)
            
            # 선택된 책의 필드 값을 가져와서 저장
            book_selection[genre] = {
                'name': genre,
                'keyword': 'keyword',
                'url': selected_book.cover,
                'isbn': selected_book.isbn13,
            }
            
            # 선택된 책을 사용 가능한 책들 리스트에서 제거
            available_books.remove(selected_book)
        else:
            book_selection[genre] = None

        gen.append(book_selection[genre])
    random.shuffle(gen)
    data = {
        'genres': gen,
    }

    return n_render(request,'recommend/prog.html', data)


def end(request):
    # 결과 페이지
    name = request.POST['name']
    isbn = request.POST['isbn']

    img = Genre.objects.filter(isbn13__icontains=isbn).values('cover')
    img = img[0]['cover']
    title = Genre.objects.filter(isbn13__icontains=isbn).values('title')
    title = title[0]['title']
    
    genre_name = name

    rg = recommend_genre(isbn)

    ra = recommend_author(isbn)

    kr = keyword_recommend(isbn)

    data = {
        "isbn" : isbn,
        "name": genre_name,
        "img" : img,
        "title" : title,
        "rg" : rg,
        "ra" : ra,
        "kr" : kr,
    }

    return n_render(request,'recommend/end.html', data)


def loading(request): # 로딩 페이지
    return n_render(request, 'recommend/loading.html')

BP/templates/recommend/end.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/recommend.css' %}">
{% endblock %}

{% block content %}

<div class = 'pict_comp'>
    <div class = 'after'>
        <h4>생성 이미지</h4>
        <img src = "/static/gen_imgs/img_{{isbn}}.png">
    </div>
    <div class='left-pointer-img-container'>
        <img class='left-pointer-img' src = "https://cdn-icons-png.flaticon.com/512/6364/6364354.png" alt = "">
    </div>
    <div class = 'before'>
        <h4>원본 이미지</h4>
        <img src = "{{ img }}" alt = "">
    </div>
    <p><h4>{{title}}</h4></p>
</div>

<div>
    <button class = "button_1" type="button" onclick = "window.location='{% url 'recommend:index' %}';">다시하기</button>
</div>
<div class='ai-recommend-title'>
    <div class='ai_content'>
        <h3>
            AI추천
        </h3>
    </div>
</div>
<div class = 'ai-recommend'>
    <div class="genre">
        <div class = "ai_genre_title">
            <h3>AI 비슷한 장르 추천</h3>
        </div>
        <div class = 'books'>
            {% for book in rg %}
            <!-- {{book}} 선택된 책들 -->
            <div class = 'book_sticker' >
                <div class = 'book_pict' >
                    <img src ="{{book.cover}}" alt = "이미지">
                </div>

                <div class = 'book_contents'>
                    <div class = 'book_name'>
                        <h4>{{book.title}}</h4>
                    </div>

                    <div class = 'book_auth'>
                        {{ book.authorName }}
                    </div>
                    <div class = 'book_link'>
                        <a href="{% url 'book:detail'%}/{{book.isbn13}}">
                        < 자세히 보기 >
                        </a>
                    </div>
                </div>
            </div>
            <!-- book sticker 종료 -->
            {% endfor %}
        </div>
    </div>
    <div class="story">
        <div class = "ai_genre_title">
            <h3>AI 비슷한 줄거리 추천</h3>
        </div>
        <div class = 'books'>
            {% for book in kr %}
            <!-- {{book}} 선택된 책들 -->
            <div class = 'book_sticker' >
                <div class = 'book_pict' >
                    <img src ="{{book.cover}}" alt = "이미지">
                </div>

                <div class = 'book_contents'>
                    <div class = 'book_name'>
                        <h4>{{book.title}}</h4>
                    </div>

                    <div class = 'book_auth'>
                        {{ book.authorName }}
                    </div>
                    <div class = 'book_link'>
                        <a href="{% url 'book:detail'%}/{{book.isbn13}}">
                        < 자세히 보기 >
                        </a>
                    </div>
                </div>
            </div>
            <!-- book sticker 종료 -->
            {% endfor %}
        </div>
    </div>
</div>
<div class='ai-recommend-title'>
    <div class='ai_content'>
        <h3>
            기타 추천
        </h3>
    </div>
</div>
<div class="author">
    <div class = "ai_genre_title">
        <h3>같은 작가가 쓴 다른 도서 목록</h3>
    </div>
    <div class = 'books'>
        {% for book in ra %}
        <!-- {{book}} 선택된 책들 -->
        <div class = 'book_sticker' >
            <div class = 'book_pict' >
                <img src ="{{book.cover}}" alt = "이미지">
            </div>

            <div class = 'book_contents'>
                <div class = 'book_name'>
                    <h4>{{book.title}}</h4>
                </div>

                <div class = 'book_auth'>
                    {{ book.authorName }}
                </div>
                <div class = 'book_link'>
                    <a href="{% url 'book:detail'%}/{{book.isbn13}}">
                    < 자세히 보기 >
                    </a>
                </div>
            </div>
        </div>
        <!-- book sticker 종료 -->
        {% endfor %}
    </div>
</div>

{% endblock %}

BP/templates/recommend/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/recommend.css' %}">
{% endblock %}

{% block content %}
<div>
    <h1>What U Want?</h1>
</div>
<div>
    <p>
        마음에 드는 그림을 선택하고, 자신에게 맞는 책을 추천받아보세요!
    </p>
</div>
<div>
    <button class = "button_1" type="button" onclick = "window.location='{% url 'recommend:loading' %}';">추천 받으러 가기</button>
</div>
{% endblock %}

BP/templates/recommend/loading.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
    <link rel="stylesheet" href="{% static 'css/personal.css' %}">
    <script type="text/javascript" src="{% static 'js/book.js' %}"></script>
{% endblock %}

{% block content %}
<div class="bookshelf_wrapper">
    <ul class="books_list">
      <li class="book_item first"></li>
      <li class="book_item second"></li>
      <li class="book_item third"></li>
      <li class="book_item fourth"></li>
      <li class="book_item fifth"></li>
      <li class="book_item sixth"></li>
    </ul>
    <div class="shelf"></div>
</div>
<div class='loading_content'>
    <div>
        <h3>AI가 지금 열심히 준비 중 이에요!</h3>
    </div>
    <div id = 'loadingText'>
        <h3>Loading...</h3>
    </div>
</div>
<input type='hidden' class = 'url' value = "{% url 'recommend:prog' %}">

<script>
    url = document.querySelector(".url").value
    window.location=url
    startLoading();
    showLoading();
</script>
{% endblock %}

BP/templates/recommend/prog.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/recommend.css' %}">
<script type="text/javascript" src="{% static 'js/recommend.js' %}"></script>
{% endblock %}
{% block content %}
    <div class = 'head'>
        <h2>What U Want?</h2>
    </div>

    <div class = 'head'>
        <h1 class = 'count'>
            1번 선택지
        </h1>
    </div>

    <div class = 'max'>    
        <div class = 'current'>
        </div>
    </div>
    <div class = 'ganre_container' >
        <div onclick = "select(1);">
            <img src ="" alt = "이미지" class = "img">
            <input type="hidden" class = "name" value = "">
            <input type="hidden" class = "keyword"  value = "">
            <input type="hidden" class = "isbn"  value = "">
        </div>

        <div onclick = "select(2);">
            <img src ="" alt = "이미지" class = "img">
            <input type="hidden" class = "name" value = "">
            <input type="hidden" class = "keyword"  value = "">
            <input type="hidden" class = "isbn"  value = "">
        </div>

        <div onclick = "select(3);">
            <img src ="" alt = "이미지" class = "img">
            <input type="hidden" class = "name" value = "">
            <input type="hidden" class = "keyword"  value = "">
            <input type="hidden" class = "isbn"  value = "">
        </div>

        <div onclick = "select(4);">
            <img src ="" alt = "이미지" class = "img">
            <input type="hidden" class = "name" value = "">
            <input type="hidden" class = "keyword"  value = "">
            <input type="hidden" class = "isbn"  value = "">
        </div>

        <form method="post" name="registerForm" onsubmit="return validateForm()" action="{% url 'recommend:end' %}" entype="application/x-www-form-urlencoded">
            {% csrf_token %}
            <input type = "hidden" class = "selected_name" name = "name">
            <input type = "hidden" class = "selected_keyword" name = "keyword">
            <input type = "hidden" class = "selected_isbn" name = "isbn">
        </form>

    </div>

    {% for genre in genres %}
        <div class = 'from_db'>
            <input type="hidden" class = "img"  value = "/static/gen_imgs/img_{{genre.isbn}}.png">
            <input type="hidden" class = "name" value = "{{genre.name}}">
            <input type="hidden" class = "keyword"  value = "{{genre.keyword}}">
            <input type="hidden" class = "isbn"  value = "{{genre.isbn}}">
        </div>
    {% endfor %}
    <script type="text/javascript">
        start()
    </script>
{% endblock %}