BP/bigsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from user.views import activate_account
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index, name='main'),
    path('about/',views.about, name='about'),
    path("board/", include('board.urls', namespace = 'board')),
    path("user/", include('user.urls', namespace = 'user')),
    path("book/", include('book.urls', namespace = 'book')),
    path("quiz/", include('quiz.urls', namespace = 'quiz')),
    path("personal/", include('personal.urls', namespace = 'personal')),
    path("recommend/", include('recommend.urls', namespace = 'recommend')),
    path('activate/<str:uidb64>/<str:token>/', activate_account, name='activate_account'),
    path('accounts/', include('allauth.urls')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # 게시판 기능
    path('', views.posts, name = 'posts'),
    path('<int:posts_id>/', views.detail, name = 'detail'),
    path('<int:posts_id>/comment_create', views.comment_create, name = 'comment_create'),
    path('posts/create/', views.post_create, name = 'post_create'),
    
    path('posts/delete/<int:posts_id>', views.del_post, name = 'del_post'),
    
    path('posts/fix/<int:posts_id>', views.post_fix, name = 'post_fix'), 
    path('posts/delcom/<int:comment_id>', views.del_post_comment, name = 'del_post_comment'),
    # 독후감 기능
    path('bookreport/create', views.bookreport_create, name = 'bookreport_create'),
    path('bookreport/', views.bookreports, name = 'bookreports'),
    path('bookreport/<int:bookreports_id>/', views.bookreport_detail, name = 'bookreport_detail'),
    path('bookreport/<int:bookreports_id>/comment_create', views.bookreport_comment_create, name = 'bookreport_comment_create'),
    
    path('bookreport/search/', views.search, name='search'),

    path('bookreport/fix/<int:bookreports_id>', views.bookreport_fix, name = 'bookreport_fix'), 
    path('bookreport/fix/search/', views.search, name='fix_search'),

    path('bookreport/delete/<int:bookreports_id>', views.del_bookreport, name = 'del_bookreport'),
    path('bookreport/delcom/<int:BookComment_id>', views.del_bookreport_comment, name = 'del_bookreport_comment'), 
]

BP/book/urls.py
# book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.list, name='list'),
    path('detail', views.detail, name='detail'),
    path('detail/<isbn>', views.detail, name='detail'),
    path('child', views.list_child, name='list_child'),
]

BP/board/models.py
from django.db import models
from user.models import User
from book.models import Books

# Create your models here.
class Posts(models.Model) : # 게시글 기능
    title = models.CharField(max_length = 100)
    book = models.ForeignKey(Books, on_delete=models.CASCADE, null=True)
    user_id = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    img_src = models.ImageField(upload_to='images/post/', blank=True, null=True)
    content = models.TextField()
    like_count = models.IntegerField(default=0)
    create_date = models.DateTimeField()
    user_nickname = models.CharField(max_length=16, null=True)

    def __str__(self) : 
        return self.title
    
class Comment(models.Model) : # 댓글 기능
    comment = models.ForeignKey(Posts, on_delete = models.CASCADE)
    content = models.CharField(max_length = 500)
    create_date = models.DateTimeField()
    user_nickname = models.CharField(max_length=16, null=True)

    
class BookReports(models.Model) : # 독후감 기능
    title = models.CharField(max_length = 100)
    book = models.ForeignKey(Books, on_delete=models.CASCADE, null=True)
    user_id = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    img_src = models.ImageField(upload_to='images/bookreport/', blank=True, null=True)
    content = models.TextField()
    like_count = models.IntegerField(default=0)
    create_date = models.DateTimeField()
    user_nickname = models.CharField(max_length = 16, null=True)
    book_title = models.TextField(null=True)
    def __str__(self) : 
        return self.title
    
class BookComment(models.Model) : # 독후감 댓글 기능
    comment = models.ForeignKey(BookReports, on_delete = models.CASCADE)
    content = models.CharField(max_length = 500)
    create_date = models.DateTimeField()
    user_nickname = models.CharField(max_length=16, null=True)

BP/board/forms.py
from django import forms
from board.models import Posts, Comment, BookReports, BookComment
class PostsForm(forms.ModelForm) :
    class Meta :
        model = Posts
        fields = ['title', 'content','img_src'] # 나중에 user_id, img_src, 추천 수 등등 필요함
        labels = {
            'title' : '제목',
            'content' : '내용',
            'img_src' : '이미지'
        }

class CommentForm(forms.ModelForm) :
    class Meta :
        model = Comment
        fields = ['content'] # 나중에 user_id, 등등 필요함
        labels = {
            'content' : '답변 내용',
        }
        
class BookReportForm(forms.ModelForm) :
    class Meta :
        model = BookReports
        fields = ['title', 'content', 'img_src']
        labels = {
            'title' : '제목',
            'content' : '내용',
            'img_src' : '이미지'
        }
        
class BookCommentForm(forms.ModelForm) :
    class Meta :
        model = BookComment
        fields = ['content']
        labels = {
            'content' : '댓글 내용'
        }

BP/board/views.py
from static.python.render_support import *
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseForbidden
from .models import Posts, BookReports, Comment, BookComment
from django.utils import timezone
from .forms import PostsForm, CommentForm, BookReportForm, BookCommentForm
from django.core.paginator import Paginator
from .models import Books
from .models import User

app_name = 'board'

def posts(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:login') + "?alert=로그인 이후에 이용하실 수 있습니다.")    
    '''목록 출력'''
    # 
    page = request.GET.get('page','1') # 페이지
    
    # 조회
    posts_list = Posts.objects.order_by('-id')
    
    # 페이징 처리
    paginator = Paginator(posts_list, 20)
    page_obj = paginator.get_page(page)
    
    posts_list = Posts.objects.order_by('-id')
    
    context = {'posts_list' : page_obj}
    
    return n_render(request, 'board/list.html', context)
    
def detail(request, posts_id) :
    '''내용 출력'''
    post = get_object_or_404(Posts, id = posts_id)
    
    # 연관된 다른 posts 예제
    relative = []
    for i in range(5):
        relative.append([post.title +' 와 관련있는 다른 글' + str(i) , 'test_id'])
    
    context = {
        'post' : post,
        'relative': relative,
        
    }
    return n_render(request, 'board/detail.html', context)

def comment_create(request, posts_id) :
    '''답변 등록'''
    post = get_object_or_404(Posts, id = posts_id)
    
    if request.method == "POST" : # 전송방식 "POST"
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.create_date = timezone.now()
            comment.post = post
            comment.comment_id = posts_id
            comment.user_nickname = request.user.nickname
            comment.save()
            return redirect('board:detail', posts_id=post.id)
    else :
        form = CommentForm()
    context = {'post' : post, 'form' : form}
    return n_render(request, 'board/detail.html', context)

def post_create(request) :
    '''게시글 등록'''
    if request.method == 'POST' : # 전송방식 "POST"
        form = PostsForm(request.POST, request.FILES) # 전송방식 "POST"
        if form.is_valid():
            posts = form.save(commit = False)
            posts.create_date = timezone.now()
            posts.user_nickname = request.user.nickname
            posts.save()
            return redirect('board:posts')
    else :
        form = PostsForm()
    context = {'form' : form}
    return n_render(request, 'board/form.html', context)

def search(request):
    query = request.GET.get('query','')

    # 검색 쿼리 실행
    if query : 
        results = Books.objects.filter(title__icontains=query).values_list('title', flat=True)
    else :
        results = []
    return JsonResponse({'results': list(results)})


def search_results(request):
    keyword = request.GET.get('keyword', '')

    # 검색 쿼리 실행
    books = Books.objects.filter(title__icontains=keyword)

    return render(request, 'board/bookreport/search_results.html', {'books': books})

def bookreport_create(request) :
    '''독후감 등록'''
    if request.method == 'POST' : # 전송방식 "POST"
        form = BookReportForm(request.POST, request.FILES) # 전송방식 "POST"
        
        if form.is_valid():
            bookreport = form.save(commit = False)
            book_title = request.POST.get('book')
            book = Books.objects.get(title=book_title)
            book_id = book.id
            book_t = book.title
            bookreport.book_id = book_id
            bookreport.book_title=book_t
            bookreport.create_date = timezone.now()
            bookreport.user_nickname = request.user.nickname
            bookreport.save()
            return redirect('board:bookreports')
    else :
        form = BookReportForm()
    context = {'form' : form}
    return n_render(request, 'board/bookreport/form.html', context)

def bookreports(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:login') + "?alert=로그인 이후에 이용하실 수 있습니다.")    
    '''독후감 목록 출력'''
    # 
    page = request.GET.get('page','1') # 페이지

    # 조회
    bookreports_list = BookReports.objects.order_by('-id')
    
    # 페이징 처리
    paginator = Paginator(bookreports_list, 20)
    page_obj = paginator.get_page(page)
    
    bookreports_list = BookReports.objects.order_by('-id')
    
    context = {'bookreports_list' : page_obj}
    
    return n_render(request, 'board/bookreport/list.html', context)

def bookreport_detail(request, bookreports_id) :
    '''독후감 내용 출력'''
    bookreport = get_object_or_404(BookReports, id = bookreports_id)
    
    # 연관된 다른 독후감 예제
    relative = []
    for i in range(5) :
        relative.append([bookreport.title +' 와 관련있는 다른 글' + str(i), 'test_id'])
        
    context = {
        'bookreport' : bookreport,
        'relative' : relative, 
    }
    return n_render(request, 'board/bookreport/detail.html', context)
    
def bookreport_comment_create(request, bookreports_id) :
    '''독후감 댓글 등록'''
    bookreport = get_object_or_404(BookReports, id = bookreports_id)
    
    if request.method == "POST" : # 전송방식 "POST"
        form = BookCommentForm(request.POST)
        if form.is_valid():
            bookcomment = form.save(commit = False)
            bookcomment.create_date = timezone.now()
            bookcomment.bookreport = bookreport
            bookcomment.comment_id = bookreports_id
            bookcomment.user_nickname = request.user.nickname
            bookcomment.save()
            return redirect('board:bookreport_detail', bookreports_id=bookreport.id)
    else :
        form = BookCommentForm()
    context = {'bookreport' : bookreport, 'form' : form}
    return n_render(request, 'board/bookreport/detail.html', context)

def post_fix(request, posts_id) :
    # 게시글 수정
    posts = get_object_or_404(Posts, id = posts_id)
    
    try : 
        post = Posts.objects.get(id = posts_id)
    except Posts.DoesNotExist : 
        return HttpResponseNotFound("게시물을 찾을 수 없습니다.")
    
    if posts.user_nickname == request.user.nickname : 
        if request.method == "POST" :
            form = PostsForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                post = form.save(commit = False)
                post.id = posts_id
                post.create_date = timezone.now()
                post.user_nickname = request.user.nickname
                post.save()
                return redirect('board:posts')
        else :
            form = PostsForm(initial={'title': post.title,
            'content': post.content,
            'img_src': post.img_src})
    
        context = {'form' : form}
        return n_render(request, 'board/form.html', context)
    else :
        return HttpResponseForbidden("글 수정 권한이 없습니다.")

def bookreport_fix(request, bookreports_id) :
    # 독후감 수정
    bookreports = get_object_or_404(BookReports, id = bookreports_id)
    
    try : 
        bookreport = BookReports.objects.get(id = bookreports_id)
    except BookReports.DoesNotExist : 
        return HttpResponseNotFound("독후감을 찾을 수 없습니다.")
    
    if bookreports.user_nickname == request.user.nickname : 
        if request.method == "POST" :
            form = BookReportForm(request.POST, request.FILES, instance=bookreport)
            if form.is_valid():
                bookreport = form.save(commit = False)
                bookreport.id = bookreports_id
                book_title = request.POST.get('book')
                book = Books.objects.get(title=book_title)
                book_id = book.id
                book_t = book.title
                bookreport.book_id = book_id
                bookreport.book_title=book_t
                bookreport.create_date = timezone.now()
                bookreport.user_nickname = request.user.nickname
                bookreport.save()
                return redirect('board:bookreports')
        else :
            form = BookReportForm(initial={'title': bookreport.title,
            'content': bookreport.content,
            'book_title' : bookreport.book_title,
            })
    
        context = {'form' : form}
        return n_render(request, 'board/bookreport/form.html', context)
    else :
        return HttpResponseForbidden("글 수정 권한이 없습니다.")
    
def del_post(request, posts_id) :
    # 게시판 삭제기능
    posts = get_object_or_404(Posts, id = posts_id)
    
    try : 
        post = Posts.objects.get(id = posts_id)
    except Posts.DoesNotExist : 
        return HttpResponseNotFound("게시물을 찾을 수 없습니다.")
    
    if posts.user_nickname == request.user.nickname : 
        post.delete()
        return redirect('board:posts')
    else : 
        #return n_render(request, 'board:list.html', {'error':'삭제할 수 없습니다.'})
        return HttpResponse("삭제할 수 없습니다.")
    
def del_bookreport(request, bookreports_id) : 
    # 독후감 삭제기능
    bookreports = get_object_or_404(BookReports, id = bookreports_id)
    
    try : 
        bookreport = BookReports.objects.get(id = bookreports_id)
    except BookReports.DoesNotExist : 
        return HttpResponseNotFound("게시물을 찾을 수 없습니다.")
    
    if bookreports.user_nickname == request.user.nickname : 
        bookreport.delete()
        return redirect('board:bookreports')
    else : 
        return HttpResponse("삭제할 수 없습니다.")
    
def del_post_comment(request, comment_id) :
    # 게시판 댓글 삭제기능
    comments = get_object_or_404(Comment, id = comment_id)
    try : 
        comment = Comment.objects.get(id = comment_id)
    except Comment.DoesNotExist : 
        return HttpResponseNotFound("댓글을 찾을 수 없습니다.")
    
    if comments.user_nickname == request.user.nickname : 
        comment.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    else : 
        return HttpResponse("삭제할 수 없습니다.")
    
def del_bookreport_comment(request, BookComment_id) :
    # 독후감 댓글 삭제기능

BP/templates/board/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/board.css' %}">
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>
{% endblock %}

{% block content %}
    <h4>[ 글 제목 ]</h4>
    <h1 class = 'title'>
        {{ post.title }}
    </h1>
    <hr>
    <div class='img-container'> 
        <h4>[ 이미지 ]</h4>
        <div class="image-wrapper">
            {% if post.img_src %}
                <img id='image' src="{{ post.img_src.url }}" alt="" style="max-width: 100%; max-height: 100%;">
            {% else%}
                <div class='no-image'>
                  <p id="no-image-text" class="hidden"><h4>첨부된 이미지가 없습니다.</h4></p>
                </div>
            {% endif %}
        </div>
        <div>
            <button id="toggle-button">접기</button>
        </div>
    </div>
    <hr>
    <div class='content-h4'>
        <h4>[ 글 내용 ]</h4>
    </div>
    <div class="board-detail">
        <pre name = "content" id="text" rows = "10" style="overflow: auto; word-wrap: break-word; resize: none; height: 500px; text-align: left; white-space: pre-wrap;">{{ post.content }}</pre>
    </div>
    <hr>

    <form action = "{% url 'board:comment_create' post.id %}"method = "post">
        {% csrf_token %}
        {% if form.errors %}
        <div role = "alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div id="form-commentInfo">
            <div id="comment-count">
                {% if post.comment_set.count == 0 %}
                  <h4>댓글 0</h4>
                {% else %}
                  <h4>댓글 {{ post.comment_set.count }}</h4>
                {% endif %}
              </div>
            <input name = "content" id="comment-input" placeholder="댓글을 입력해 주세요.">
            <button id="submit">등록</button>
        </div>
    </form>
    <div class='comment-container'>
        {% for post in post.comment_set.all %}
        <div id='comments'>
            <p class='comment-user'><strong>User: {{ post.user_nickname }}</strong></p><br>
            <a class='btn-del' href="{% url 'board:del_post_comment' comment_id=post.id%}">댓글삭제</a>
            <p>{{ post.content }}</p>
        </div>
        {% endfor %}
    </div>
    <br>
    <div class='save-location'>
        <a class='btn-back' href="{% url 'board:post_fix' posts_id=post.id%}">수정</a>
        <a class='btn-back' href="{% url 'board:del_post' posts_id=post.id%}">삭제</a>
        <a class='btn-back' href="{% url 'board:posts'%}">뒤로가기</a>
    </div>

    <script>
        const toggleButton = document.getElementById('toggle-button');
        const noImageText = document.getElementById('no-image-text');
    
        toggleButton.addEventListener('click', function() {
            const imageWrapper = document.querySelector('.image-wrapper');
    
            if (imageWrapper) {
                if (imageWrapper.classList.contains('hidden')) {
                    imageWrapper.classList.remove('hidden');
                    noImageText.classList.add('hidden');
                    toggleButton.textContent = '접기';
                } else {
                    imageWrapper.classList.add('hidden');
                    noImageText.classList.remove('hidden');
                    toggleButton.textContent = '펼치기';
                }
            }
        });
    </script>
{% endblock %}

BP/templates/board/fix.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/board.css' %}">
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>
{% endblock %}

{% block content %}
<h1>글 수정</h1>
<div id="wrapper">
    <form id="paper" method = "post" enctype="multipart/form-data"> <!-- 전송 방식 : post-->
        {% csrf_token %}
        
        <!-- 오류 표시 시작-->
        {% if form.errors %}
            <div role = "alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 표시 종료-->
        <!-- form -->
        <div class = 'input_divs'>
            <input type = "text" name = "title" class='input_1' placeholder="Title" value = "{{ form.title.value|default_if_none:''}}">{{ post.title }}</input>
        </div>
        <br>
        <div>
            <textarea name = "content" id="text" rows = "10" style="overflow: auto; word-wrap: break-word; resize: none; height: 500px; ">{{ form.content.value|default_if_none:''}}{{post.content}}</textarea>
        </div>
        <br>
        <div class="container">
            <label class="label" id="label" for="input">
               <div class="inner" id="inner">Drag or Click for Upload</div>
            </label>
            <input id="input" class="input" name = 'img_src' accept="image/*" type="file" multiple="true" hidden="true">{{post.img_src}}</input>
            <p class="preview-title">preview</p>
            <div class="preview" id="preview"></div>
        </div>
        <hr>
        <br>
        <div class='save-location'>
        <!-- {{ form.as_p }} 오류 표시 추가 하면서 수정-->
        <a class='btn-back' href="{% url 'board:posts'%}">뒤로가기</a>
        <button type= "submit">저장하기</button>
        </div>
    </form>
</div>


 
 <script>
    var input = document.getElementById("input");
    var initLabel = document.getElementById("label");
 
    input.addEventListener("change", (event) => {
       const files = changeEvent(event);
       handleUpdate(files);
    });
 
    initLabel.addEventListener("mouseover", (event) => {
       event.preventDefault();
       const label = document.getElementById("label");
       label?.classList.add("label--hover");
    });
 
    initLabel.addEventListener("mouseout", (event) => {
       event.preventDefault();
       const label = document.getElementById("label");
       label?.classList.remove("label--hover");
    });
 
    document.addEventListener("dragenter", (event) => {
       event.preventDefault();
       console.log("dragenter");
       if (event.target.className === "inner") {
          event.target.style.background = "#616161";
       }
    });
 
    document.addEventListener("dragover", (event) => {
       console.log("dragover");
       event.preventDefault();
    });
 
    document.addEventListener("dragleave", (event) => {
       event.preventDefault();
       console.log("dragleave");
       if (event.target.className === "inner") {
          event.target.style.background = "#3a3a3a";
       }
    });
 
    document.addEventListener("drop", (event) => {
       event.preventDefault();
       console.log("drop");
       if (event.target.className === "inner") {
          const files = event.dataTransfer?.files;
          event.target.style.background = "#3a3a3a";
          handleUpdate([...files]);
       }
    });
 
    function changeEvent(event) {
       const { target } = event;
       return [...target.files];
    };
 
    function handleUpdate(fileList) {
       const preview = document.getElementById("preview");
 
       fileList.forEach((file) => {
          const reader = new FileReader();
          reader.addEventListener("load", (event) => {
             const img = el("img", {
                className: "embed-img",
                src: event.target?.result,
             });
             const imgContainer = el("div", { className: "container-img" }, img);
             preview.append(imgContainer);
          });
          reader.readAsDataURL(file);
       });
    };
 
    function el(nodeName, attributes, ...children) {
       const node =
          nodeName === "fragment"
             ? document.createDocumentFragment()
             : document.createElement(nodeName);
 
       Object.entries(attributes).forEach(([key, value]) => {
          if (key === "events") {
             Object.entries(value).forEach(([type, listener]) => {
                node.addEventListener(type, listener);
             });
          } else if (key in node) {
             try {
                node[key] = value;
             } catch (err) {
                node.setAttribute(key, value);
             }
          } else {
             node.setAttribute(key, value);
          }
       });
 
       children.forEach((childNode) => {
          if (typeof childNode === "string") {
             node.appendChild(document.createTextNode(childNode));
          } else {
             node.appendChild(childNode);
          }
       });
 
       return node;
    }
 </script>


{% endblock %}

BP/templates/board/list.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
<!-- 추가적으로 적용할 CSS 는 이쪽으로, 순서가 뒤 이면 overwrite 함 -->
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/board.css' %}">
{% endblock %}

{% block content %}
<div>
    <h1>자유게시판</h1>
<div>
<div id="free_board_btn_group">
    <a id="board_btn1" href="{% url 'board:posts'%}">자유게시판</a>
    <a id="board_btn3" href="{% url 'board:bookreports'%}">독후감게시판</a>
</div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th style = "flex: 11;">Title</th>
                <th>User</th>
                <th style = "flex: 2;">Comments</th>
            </tr>
        </thead>
        <tbody>
            {% if posts_list %}
                {% for post in posts_list%}
                    <tr class="alert" role="alert" onclick = "window.location='{% url 'board:posts' %}{{post.id}}/';">
                        <th class="centered-td" scope="row">{{ post.id }}</th>
                        <td class="centered-td" style = "text-align: center; font-weight:bold; flex: 11;">{{ post.title }}</td>
                        <td class="centered-td">{{post.user_nickname}}</td>
                        <td class="centered-td" style = "flex: 2;">{{ post.comment_set.count }}</td>   
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <p>게시글이 없습니다.</p>
                </tr>
            {% endif %}
        </tbody>
    </table>
    <div class='page-wrap'>
    <!-- 페이징 처리 시작-->
        <ul class='page-nation'>
            <!-- 이전 페이지 -->
            {% if posts_list.has_previous %}
            <li>
                <a href = "?page={{posts_list.previous_page_number}}"><<</a>
            </li>
            {% else %}
            <li>
                <a href = "#"><<</a>
            </li>
            {% endif %}
            <!-- 페이지 리스트 -->
            {% for page_number in posts_list.paginator.page_range %}
            {% if page_number >= posts_list.number|add:-5 and page_number <= posts_list.number|add:5 %}
                {% if page_number == posts_list.number %}
                <li aria-current = "page">
                    <a href = "?page={{ page_number }}">
                        {{page_number}}
                    </a>
                </li>
                {% else %}
                <li>
                    <a href = "?page={{page_number}}">
                        {{ page_number }}
                    </a>
                </li>
                {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음 페이지 -->
            {% if posts_list.has_next%}
            <li>
                <a href = "?page={{posts_list.next_page_number}}">>></a>
            </li>
            {% else %}
            <li>
                <a href = "#">>></a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징 처리 끝-->
    </div>
    <div class="btn-container">
        <a class='btn' href = "{% url 'board:post_create' %}">
            글쓰기
        </a>
    </div>
    {% if error %}
    <div class='error-message'>{{error}}</div>
    {% endif %}
{% endblock %}