BP/bigsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from user.views import activate_account
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index, name='main'),
    path('about/',views.about, name='about'),
    path("board/", include('board.urls', namespace = 'board')),
    path("user/", include('user.urls', namespace = 'user')),
    path("book/", include('book.urls', namespace = 'book')),
    path("quiz/", include('quiz.urls', namespace = 'quiz')),
    path("personal/", include('personal.urls', namespace = 'personal')),
    path("recommend/", include('recommend.urls', namespace = 'recommend')),
    path('activate/<str:uidb64>/<str:token>/', activate_account, name='activate_account'),
    path('accounts/', include('allauth.urls')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # 게시판 기능
    path('', views.posts, name = 'posts'),
    path('<int:posts_id>/', views.detail, name = 'detail'),
    path('<int:posts_id>/comment_create', views.comment_create, name = 'comment_create'),
    path('posts/create/', views.post_create, name = 'post_create'),
    
    path('posts/delete/<int:posts_id>', views.del_post, name = 'del_post'),
    
    path('posts/fix/<int:posts_id>', views.post_fix, name = 'post_fix'), 
    path('posts/delcom/<int:comment_id>', views.del_post_comment, name = 'del_post_comment'),
    # 독후감 기능
    path('bookreport/create', views.bookreport_create, name = 'bookreport_create'),
    path('bookreport/', views.bookreports, name = 'bookreports'),
    path('bookreport/<int:bookreports_id>/', views.bookreport_detail, name = 'bookreport_detail'),
    path('bookreport/<int:bookreports_id>/comment_create', views.bookreport_comment_create, name = 'bookreport_comment_create'),
    
    path('bookreport/search/', views.search, name='search'),

    path('bookreport/fix/<int:bookreports_id>', views.bookreport_fix, name = 'bookreport_fix'), 
    path('bookreport/fix/search/', views.search, name='fix_search'),

    path('bookreport/delete/<int:bookreports_id>', views.del_bookreport, name = 'del_bookreport'),
    path('bookreport/delcom/<int:BookComment_id>', views.del_bookreport_comment, name = 'del_bookreport_comment'), 
]

BP/book/urls.py
# book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.list, name='list'),
    path('detail', views.detail, name='detail'),
    path('detail/<isbn>', views.detail, name='detail'),
    path('child', views.list_child, name='list_child'),
]

BP/personal/urls.py
# personal/urls.py
from django.urls import path
from . import views

app_name = 'personal'
urlpatterns = [
    path('', views.index, name='index'),
    path('loading/', views.loading, name='loading'),
]

BP/quiz/urls.py
# quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='index'),
    path('prog', views.prog, name='prog'),
    path('end', views.end, name='end'),
]

BP/user/urls.py
# user_app/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('register/', views.user_form_view, name='register'),
    path('register/check-username/', views.check_username, name='check_username'),
    path('select/', views.select, name='select'),
    path('login/', views.login_view, name='login'),
    path('forgot_id/', views.forgot_id, name='forgot_id'),
    path('forgot_pw/', views.forgot_pw, name='forgot_pw'),
    path('forgot_pw/<str:uid>/<str:token>/', views.forgot_pw, name='forgot_pw'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('mypage/', views.mypage, name='mypage'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete_check, name='delete_check'),
    path('delete_/', views.delete_real, name='delete_real'),
]

BP/templates/base/base.html
{% load static %}
<html>
    <head>
        <title>  책크미  </title>
        {% block title %}
        {% endblock %}
        
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        <link rel="icon" type="image/png" href="{% static 'images/img_02.png' %}">
        {% if alert != '' %}
            <script>
                // get 방식으로 url/?alert=~~~ 하고 넣으면 해당 값이 출력됨
                alert(" {{ alert }} ");
            </script>
        {% endif %}
        <!-- Additional CSS Files -->
        {% block extrahead %}
        {% endblock %}
    </head>
    <div class = 'topnav'>
        <!-- leftside_aligned -->
        <a href="/">
            <div class = 'ingredients'>
                <h2 style='margin-top:-5px;'>CheckMe</h2>
            </div>
        </a>
        
        <!-- rightside_aligned -->
        {% if user.is_authenticated %}
            <a href="{% url 'user:mypage'%}">
                <div class = 'ingredients user_alter'>
                    <h4>내 정보</h4>
                </div>
            </a>
            
            <a href="{% url 'user:logout' %}">
                <div class = 'ingredients user_alter'>
                    <h4>로그아웃</h4>
                </div>
            </a>
        {% else %}
            <a href="{% url 'user:register' %}">
                <div class = 'ingredients user_alter'>
                    <h4>회원가입</h4>
                </div>
            </a>
            <a href="{% url 'user:login' %}">
                <div class = 'ingredients user_alter'>
                    <h4>로그인</h4>
                </div>
            </a>
        {% endif %}
        
        
        
    </div>
    <div class = 'sidenav_caller' onclick = 'call_sidenav()'>
        =
    </div>
    <div class = 'sidenav'>
        <div class = 'ingredients' id = 'sidenav_closer' onclick = 'kill_sidenav()'>
            &lt;    <!-- 얘 지우면 버튼이 안보여요 -->
        </div>
        <div></div>

        <a href="/">
            <div class = 'ingredients2'>
                <h2>CheckMe</h2>
            </div><br>
        </a> 

        {% comment %} <a href="{% url 'about'%}">
            <div class = 'ingredients ingr_clk'>
                About
            </div>
        </a><br><br> {% endcomment %}

        <a href="{% url 'personal:loading'%}">
            <div class = 'ingredients ingr_clk'>
                Personal Book
            </div><br>
        </a>
        <a href="{% url 'recommend:index'%}">
            <div class = 'ingredients ingr_clk'>
                What U Want?
            </div><br>
        </a>
        
        <a href="{% url 'quiz:index'%}">
            <div class = 'ingredients ingr_clk'>
                Book Quiz
            </div><br><br>
        </a>

        <a href="{% url 'book:list' %}">
            <div class = 'ingredients ingr_clk'>
                도서 검색
            </div><br>
        </a>
        
        <div class = 'ingredients2'>
            게시판
        </div><br>

        <a href="{% url 'board:posts'%}">
            <div>
                &emsp;&emsp;<p class = 'ingredients ingr_clk'>자유 게시판</p>
            </div>
        </a>

        <a href="{% url 'board:bookreports'%}">
            <div>
                &emsp;&emsp;<p class = 'ingredients ingr_clk'>독후감 게시판</p>
            </div><br>
        </a>

        <div class='line_div'></div>

        {% if user.is_authenticated %}
            <a href="{% url 'user:mypage'%}">
                <div class = 'ingredients ingr_clk'>
                    내 정보
                </div><br>
            </a>
            
            <a href="{% url 'user:logout' %}">
                <div class = 'ingredients ingr_clk'>
                    로그아웃
                </div><br>
            </a>

        {% else %}
            <a href="{% url 'user:register' %}">
                <div class = 'ingredients ingr_clk'>
                    회원가입
                </div><br>
            </a>
            <a href="{% url 'user:login' %}">
                <div class = 'ingredients ingr_clk'>
                    로그인
                </div><br>
            </a>
        {% endif %}
    </div>
    <body>

        <button id="scrollButton_main" onclick="scrollToTop()" style='border:1px solid #000;'></button>

        <div class = 'content_div'>
            {% block content %}
            {% endblock %}
        </div>
        <hr>
        <div class = 'footer'>
            <h5>나의 감성을 저격하는 이미지 기반 독자 맞춤형 도서 추천 서비스</h5><br>
            <small><h5>위 사이트는 '알라딘 서점' API 의 데이터 베이스를 이용하여 제작되었습니다.</h5></small><br>
            <small><h5>KT AIVLE SCHOOL AI TRACK 1반 1조</h5></small><br>
        </div>
    </body>
    
</html>